### ISSUE TITLE
cant I cannot log into the account directly through the email and password.

### ISSUE THREAD

**Issue by omarhazazi1** [tigr1234566/TikTokMod#1]
I cannot log into the account directly through the email and password. The previous update was possible to log into the account by typing the email and password and then login directly without using Google, please solve the problem.

**Comment by omarhazazi1** [comment]
![Uploading IMG_٢٠٢٢٠٤٠٨_١٦٤٨٥٤.jpg…]()

**Comment by tigr1234566** [comment]
> I cannot log into the account directly through the email and password. The previous update was possible to log into the account by typing the email and password and then login directly without using Google, please solve the problem.

Fixed with new release
