### ISSUE TITLE
Spinning App Issue

### ISSUE THREAD

**Issue by ItsPasi** [tigr1234566/TikTokMod#9]
Not sure if this is the official repo for TikTokModCloud but this is linked on their page so.

The TikTok app spins 3 times for it's transition animation. This was introduced sometime this year and should be undone/animation should be removed.

https://github.com/tigr1234566/TikTokMod/assets/12584747/51e5b717-0ff0-416e-8d02-e432c31a60a4

**Comment by tigr1234566** [comment]
Turn off phone animation

**Comment by ItsPasi** [comment]
> Turn off phone animation

That's not a permanent solution

**Comment by tigr1234566** [comment]
> > Turn off phone animation
> 
> That's not a permanent solution

Its bug from official app
